// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Load env files the same way Next.js does so the Prisma CLI and the running
// app always resolve the SAME DATABASE_URL. Precedence (highest first):
//   1. real environment variables (shell / PM2) — never overridden by dotenv
//   2. .env.local
//   3. .env
// dotenv does not override already-set keys, so loading .env.local before
// .env gives .env.local priority while leaving real env vars untouched.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
